
# slave name differs from default
SLAVE := Unit-A.Slave
SLAVESRC := unit-a.s
# where to install via 'make dest'
DEST := cwart:UnitA\ FA18Interceptor
# no install script, directly runnable
NOINSTALL := true
# additional files to copy from 'inst' to install directory
INSTFILES := unit-a rage

include ../../Makemacros

