	IFND UTILITY_TAGITEM_I
UTILITY_TAGITEM_I SET 1
 IFND EXEC_TYPES_I
 INCLUDE "exec/types.i"
 ENDC
 STRUCTURE TagItem,0
 ULONG ti_Tag
 ULONG ti_Data
 LABEL ti_SIZEOF
TAG_DONE=0
TAG_END=0
TAG_IGNORE=1
TAG_MORE=2
TAG_SKIP=3
TAG_USER=$80000000
TAGFILTER_AND=0
TAGFILTER_NOT=1
MAP_REMOVE_NOT_FOUND=0
MAP_KEEP_NOT_FOUND=1
 ENDC
