	IFND EXEC_PORTS_I
EXEC_PORTS_I SET 1
 IFND EXEC_NODES_I
 INCLUDE "exec/nodes.i"
 ENDC
 IFND EXEC_LISTS_I
 INCLUDE "exec/lists.i"
 ENDC
 STRUCTURE MP,LN_SIZE
 UBYTE MP_FLAGS
 UBYTE MP_SIGBIT
 APTR MP_SIGTASK
 STRUCT MP_MSGLIST,LH_SIZE
 LABEL MP_SIZE
MP_SOFTINT= MP_SIGTASK
PF_ACTION= 3
PA_SIGNAL= 0
PA_SOFTINT= 1
PA_IGNORE= 2
 STRUCTURE MN,LN_SIZE
 APTR MN_REPLYPORT
 UWORD MN_LENGTH
 LABEL MN_SIZE
 ENDC
