
# where to install via 'make dest'
DEST := cwart:AgilePunishers\ BartSpace
# no install script, directly runnable
NOINSTALL := true
# additional files to copy from 'inst' to install directory
INSTFILES := AGILE PNS91

include ../../Makemacros

