	IFND GRAPHICS_GFXNODES_I
GRAPHICS_GFXNODES_I=1
 IFND EXEC_TYPES_I
 include 'exec/types.i'
 ENDC
 STRUCTURE XLN,0
 APTR XLN_SUCC
 APTR XLN_PRED
 UBYTE XLN_TYPE
 BYTE XLN_PRI
 APTR XLN_NAME
 UBYTE XLN_SUBSYSTEM
 UBYTE XLN_SUBTYPE
 LONG XLN_LIBRARY
 LONG XLN_INIT
 LABEL XLN_SIZE
SS_GRAPHICS=$02
VIEW_EXTRA_TYPE=1
VIEWPORT_EXTRA_TYPE=2
SPECIAL_MONITOR_TYPE=3
MONITOR_SPEC_TYPE=4
 ENDC
