
# slave name differs from default
SLAVE := BlackMonks.Slave
# where to install via 'make dest'
DEST := cwart:BlackMonks\ TestDrive2
# no install script, directly runnable
NOINSTALL := true
# additional files to copy from 'inst' to install directory
INSTFILES := BlackMonks

include ../../Makemacros

