	IFND LIBRARIES_NONVOLATILE_I
LIBRARIES_NONVOLATILE_I SET 1
 IFND EXEC_TYPES_I
 INCLUDE "exec/types.i"
 ENDC
 IFND EXEC_NODES_I
 INCLUDE "exec/nodes.i"
 ENDC
 STRUCTURE NVInfo,0
 ULONG nvi_MaxStorage
 ULONG nvi_FreeStorage
 LABEL NVINFO_SIZE
 STRUCTURE NVEntry,0
 STRUCT nve_Node,MLN_SIZE
 APTR nve_Name
 ULONG nve_Size
 ULONG nve_Protection
 LABEL NVENTRY_SIZE
 BITDEF NVE,DELETE,0
 BITDEF NVE,APPNAME,31
NVERR_BADNAME=1
NVERR_WRITEPROT=2
NVERR_FAIL=3
NVERR_FATAL=4
SizeNVData MACRO
 move.l -4(/1),/2
 subq.l #4,/2
 ENDM
 ENDC
