
# slave name differs from default
SLAVE := BamigaSectorOne-GPC.Slave
# where to install via 'make dest'
DEST := cwart:BamigaSectorOne\ GrandPrix
# no install script, directly runnable
NOINSTALL := true
# additional files to copy from 'inst' to install directory
INSTFILES := bs1*

include ../../Makemacros

