	IFND DOS_RDARGS_I
DOS_RDARGS_I SET 1
 IFND EXEC_NODES_I
 INCLUDE "exec/nodes.i"
 ENDC
 STRUCTURE CSource,0
 APTR CS_Buffer
 LONG CS_Length
 LONG CS_CurChr
 LABEL CS_SIZEOF
 STRUCTURE RDArgs,0
 STRUCT RDA_Source,CS_SIZEOF
 APTR RDA_DAList
 LONG RDA_Buffer
 LONG RDA_BufSiz
 APTR RDA_ExtHelp
 LONG RDA_Flags
 LABEL RDA_SIZEOF
 BITDEF RDA,STDIN,0
 BITDEF RDA,NOALLOC,1
 BITDEF RDA,NOPROMPT,2
MAX_TEMPLATE_ITEMS=100
MAX_MULTIARGS=128
 ENDC
