
# slave name differs from default
SLAVE := WorldOfWonders.Slave
SLAVESRC := worldofwonders.s
# where to install via 'make dest'
DEST := cwart:WorldOfWonders/CrazyCars2
# no install script, directly runnable
NOINSTALL := true
# additional files to copy from 'inst' to install directory
INSTFILES := wow-crak.exe

include ../../Makemacros

